name: Terraform Apply via PR Comment

# Trigger on PR comments
on:
  issue_comment:
    types: [created] # Only trigger on new comments

jobs:
  terraform-apply:
    # Only run if comment is on a PR and contains /apply
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        # Pulls the PR branch code into the runner

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7
        # Ensures Terraform version consistency

      # Step 3: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Allows Terraform to authenticate with AWS

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        # Prepares Terraform (downloads providers/modules)

      # Step 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        # Actually applies changes to AWS
        # -auto-approve skips interactive approval
