name: Terraform Apply via PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  terraform-apply:
    # Run only if comment is on a PR and contains "/apply"
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      # Step 3: Configure AWS credentials (environment vars)
      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Apply
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color | tee apply_output.txt

      # Step 6: Comment Apply Output in PR
      - name: Comment Apply Output on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### 🚀 Terraform Apply Result
            ```
            ${{ steps.apply.outputs.stdout }}
            ```

