name: Terraform Checks

on:
  pull_request:
    branches: [ "main" ]
<<<<<<< HEAD

permissions:
  contents: read
  pull-requests: write
  issues: write
=======
>>>>>>> 484e0357543d6d7ab46bb3d9d716e2f062e2eed2

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout Code
        uses: actions/checkout@v3

=======
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
>>>>>>> 484e0357543d6d7ab46bb3d9d716e2f062e2eed2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

<<<<<<< HEAD
=======
      # Set AWS credentials as env vars
>>>>>>> 484e0357543d6d7ab46bb3d9d716e2f062e2eed2
      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

<<<<<<< HEAD
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color > plan.txt

      - name: Comment Plan on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### ✅ Terraform Plan Output
            ```
            ${{ steps.plan.outputs.stdout }}
            ```

=======
      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
>>>>>>> 484e0357543d6d7ab46bb3d9d716e2f062e2eed2
